Refresh access token
konstantinlob/What-am-I-listening-to pull request #11
Opened 2022-09-27 16:25 UTC by JuliusJaenchen

2022-09-27 16:32 UTC, roriwa commented on pages/login.vue
> +    if (localStorage.getItem("auth-token") !== null) {
```suggestion
    if (localStorage.getItem("auth-token")) {
```

2022-09-27 16:45 UTC, roriwa commented on pages/auth.vue
>      tradeCodeForToken();
Der name `tradeCodeForToken` würde eher so etwas suggestieren, was ich auch besser finden würde
```suggestion
    const params = ...
    if(params.error) ...
    const code = params.get('code')
    const token = tradeCodeForToken(code);
    ...
```

2022-09-27 16:45 UTC, roriwa commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken() {
siehe pages/auth.vue

diese funktion sollte etwas weniger machen

2022-09-27 16:45 UTC, roriwa commented on app.vue
> +  refreshAccessToken();
wie oft wird das aufgerufen? nur wenn man das erste mal auf unsere seite geht (/refresh), oder auch wenn man per nuxt-link die page ändert?

2022-09-27 16:45 UTC, roriwa commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken() {
bzw. man weiß eig. nicht wirklich von wo die aufgerufen wird und dann kommen da die sachen mit `window.location.search` etc.

2022-09-27 17:19 UTC, JuliusJaenchen commented on app.vue
> +  refreshAccessToken();
Das wird (wenn ich es richtig verstanden habe) nur einmal per page load ausgeführt. Bei einem navigateTo() sollte es nicht nochmal ausgeführt werden.

Das musste ich hinzufügen, da sonst das refreshAccessToken bei einem page refresh kaputt ging.

2022-09-27 17:22 UTC, JuliusJaenchen commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken() {
Stimmt, das verbessere ich. Danke!

2022-09-27 17:27 UTC, JuliusJaenchen commented on pages/login.vue
> +    if (localStorage.getItem("auth-token") !== null) {
Das funktioniert auch, aber der explizite null comparison ist spezifischer. Da localStorage explizit `null` zurück gibt, wenn der key nicht existiert, fand ich es angemessen spezifischer zu sein.

2022-09-28 07:10 UTC, roriwa requested changes
falscher name für parameter (sonst alles gut)

2022-09-28 07:10 UTC, roriwa commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken(codeChallenge: string, redirectUrl: URL) {
das ist nicht `codeChellange`. mit `code` ist der pkce (proof key) gemeint.
Code chellange war das extra zur verifizierung und sicherheit

2022-09-28 07:10 UTC, roriwa commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken(codeChallenge: string, redirectUrl: URL) {
(das was aus dem code-verifier generiert wurde)

2022-09-28 07:37 UTC, JuliusJaenchen commented on assets/ts/auth/access-token.ts
> +export function tradeCodeForToken(codeChallenge: string, redirectUrl: URL) {
stimmt, das hatte ich verwechselt, danke

2022-09-28 07:39 UTC, roriwa requested changes

2022-09-28 07:39 UTC, roriwa commented on pages/auth.vue
> +    } if (params.has("error")) {
entweder das if in eine neue zeile, oder das ganze zu einem else-if machen

2022-09-28 08:23 UTC, roriwa approved these changes

2022-09-28 08:25 UTC, merged