replaced yarn in README with npm
konstantinlob/What-am-I-listening-to pull request #24
Opened 2022-10-02 19:05 UTC by roriwa

2022-10-02 20:01 UTC, JuliusJaenchen commented on README.md
> +npm run build
Ich glaube deploy baut es für production. Postdeploy deployed es dann. So wie du es in der readme beschrieben hast macht es aber sinn. Willst du es auch in der package.json anpassen?

2022-10-04 14:15 UTC, JuliusJaenchen requested changes

2022-10-04 14:26 UTC, roriwa commented on README.md
> +Make a build if the application for production:
@JuliusJaenchen typo. soll heißen `Make a build of`. welche soll ich nehmen?

2022-10-04 16:54 UTC, JuliusJaenchen commented on README.md
> +Make a build if the application for production:
Ah. Nur Build klingt immernoch schöner find ich

2022-10-06 19:37 UTC, merged