included the new /introduction path to the app
konstantinlob/What-am-I-listening-to pull request #30
Opened 2022-10-03 13:16 UTC by roriwa

2022-10-03 18:51 UTC, JuliusJaenchen commented on pages/index.vue
> +        if(localStorage.getItem('introduced')){
Du könntest in den conditions spezifischer sein. Also "=== null" und "=== true" explizit ransetzen. Dann sieht man sofort was für ein Rückgabewert du erwartest, und muss nicht raten oder Kontext wissen haben.

2022-10-03 18:51 UTC, JuliusJaenchen commented on pages/index.vue
>  <script lang="ts" setup>
Vielleicht könnte man diese Redirect Logik in eine separate assets/ts Funktion auslagern, damit man sie auch auf anderen Seiten als erstes ausführen kann.

2022-10-04 14:16 UTC, JuliusJaenchen requested changes
Merge Konflikte lösen und `npm run lint` ausführen bitte

2022-10-04 14:16 UTC, JuliusJaenchen commented on pages/index.vue
>      if(!localStorage.getItem('auth-token')){
```suggestion
    if(localStorage.getItem('auth-token') === null){
```

2022-10-04 14:16 UTC, JuliusJaenchen commented on pages/index.vue
> +        }
```suggestion
        if(localStorage.getItem('introduced') === "true"){
            navigateTo("/login");
        } else {
            localStorage.setItem('introduced', "true");
            navigateTo("/introduction");
        }
```

2022-10-04 14:27 UTC, roriwa commented on pages/index.vue
> +        }
@JuliusJaenchen ich würde eig. lieber weniger value abhängig machen und würde deshalb !== null bevorzugen

2022-10-04 14:49 UTC, JuliusJaenchen commented on pages/index.vue
> +        }
alright, aber dann würde ich wenigstens die Kommentare rausmachen. Der erste ist klar und der zweite könnte schnell veralten.

2022-10-07 13:52 UTC, JuliusJaenchen commented on pages/index.vue
> +        if(localStorage.getItem('introduced') !== null){
```suggestion
        if(localStorage.getItem('introduced') === "true"){
```
Ich weiß es ist nicht notwendig, aber es ist meiner meinung nach sehr viel leichter lesbar

2022-10-07 13:53 UTC, JuliusJaenchen commented on pages/introduction.vue
> +        navigateTo('/login');
kannst du navigateTo() gleich im template einsetzen? dann brauchen wir routeToExploration nicht mehr.

2022-10-07 15:45 UTC, JuliusJaenchen approved these changes

2022-10-07 15:51 UTC, merged