Iceberg statistics
konstantinlob/What-am-I-listening-to pull request #44
Opened 2022-10-10 08:10 UTC by roriwa

2022-10-12 14:38 UTC, JuliusJaenchen requested changes

2022-10-12 14:38 UTC, JuliusJaenchen commented on components/Statistics/Iceberg/Iceberg.vue
> +<script lang="ts" setup>
Wollen wir IceBerg auch in assets/vue verlagern?
Ich fände es übersichtlich, wenn alles in components/Statistics/ einen konkreten "Slide" im Karusell darstellt.

2022-10-12 14:38 UTC, JuliusJaenchen commented on components/Statistics/Iceberg/TopArtists.vue
> +    console.log(artists);
forgotten console.log

2022-10-12 14:38 UTC, JuliusJaenchen commented on components/Statistics/Iceberg/TopArtists.vue
> +        const data: TopArtists = await request<TopArtists>({
wir können ja sowieso nur <50 Artists anzeigen. Dann lass lieber nur ein request machen, wo wir das limit auf 50 oder so setzen.

2022-10-12 14:38 UTC, JuliusJaenchen commented on components/Statistics/Iceberg/TopArtists.vue
> +    const artists: Artist[] = Object.values(artistIndex);
wenn man nur einen request macht, kann man ja auch nur `artists = response.items` machen

2022-10-12 14:38 UTC, JuliusJaenchen commented on components/Statistics/Iceberg/RecentlyPlayedTracks.vue
> +<script lang="ts" setup>
RecentlyPlayedTracks würde ich nicht in diesem PR mitnehmen.
1. Es ist in Fällen von nicht so aktiven Nutzern identisch zu TopTracks.
2. Es passt nicht zu der Timeframe selection oben. Das führt einige Probleme ein, die geklärt werden müssen, bevor wir das einbinden können.

Wenn die Komponente dir am herzen liegt, können wir das in einem anderen PR nachziehen

2022-10-12 17:46 UTC, roriwa commented on assets/ts/api/types/generell/Album.ts
> +import { Artist } from "./";
hat einwandfrei funktioniert, deshalb hatte ich es gelassen

2022-10-13 09:06 UTC, JuliusJaenchen commented on assets/ts/api/types/generell/Album.ts
> +import { Artist } from "./";
ah, ok, dann war es ein React problem.

2022-10-13 09:08 UTC, JuliusJaenchen reviewed
pls fix merge conflicts

2022-10-14 15:37 UTC, roriwa commented on assets/ts/api/request.ts
> +    }).then(async (response) => {
funktioniert async hier wirklich? (bin neugierig)

2022-10-14 15:49 UTC, JuliusJaenchen commented on assets/ts/api/request.ts
> +        await navigateTo("/login");
Ja. Aber ich wollte auch unabhängig davon auch das redirecting an dieser stelle fixen. Ich habe noch nicht rausfinden können ob es so funktioniert.

2022-10-15 09:48 UTC, JuliusJaenchen commented on assets/ts/api/request.ts
> +    }).then(async (response) => {
Async arrow Funktions gibt es. Ich bin auch noch nicht überzeugt, dass es hier funktioniert😂. typeScript mag es zumindest

2022-10-15 09:49 UTC, JuliusJaenchen commented on components/Statistics/ArtistIceberg.vue
> +<template>
Richtig cool natürlich😎🥶😁

2022-10-15 09:52 UTC, JuliusJaenchen commented on components/Statistics/ArtistIceberg.vue
> +<template>
Spaß. Die Images sind statisch auf dem Iceberg angeordnet, und Unterwasser sind sie als langweiliges Grid angeordnet. Die Slots werden reihenweise (nach popularity) gefüllt und bleiben ggf. Leer. Zudem wird innerhalb einer row  die Reihenfolge randomized, sodass die Bilder nicht alle am linken Rand sind.

2022-10-15 15:09 UTC, closed without merging