artist iceberg
konstantinlob/What-am-I-listening-to pull request #54
Opened 2022-10-15 15:10 UTC by JuliusJaenchen

2022-10-16 14:31 UTC, roriwa requested changes
keine ahnung, irgendwie mag ich diesen eisberg nicht ganz. ist mir etwas zu leer/nichts-aussagend

2022-10-16 14:31 UTC, roriwa commented on app.vue
> +    import { refreshAccessToken } from "./assets/ts/auth";
warum `.` und nicht `~`?

2022-10-16 14:31 UTC, roriwa commented on components/Statistics/ArtistIceberg.vue
> +    const response: TopArtists = await request<TopArtists>({
entweder `topArtists` oder `result`. response klingt zu sehr nach dem "rohen" object (`fetch(): Promis<Response>`)

2022-10-16 14:31 UTC, roriwa commented on components/Statistics/ArtistIceberg.vue
> +                <template v-for="(item, index) in orderedItems.slice(8, 29)" :key="index + item">
klappt das mit diesen klammern? (sollte man nicht `[]` verwenden?)

2022-10-17 10:18 UTC, JuliusJaenchen commented on app.vue
> +    import { refreshAccessToken } from "./assets/ts/auth";
war ausversehen, danke

2022-10-17 10:27 UTC, JuliusJaenchen commented on components/Statistics/ArtistIceberg.vue
> +                <template v-for="(item, index) in orderedItems.slice(8, 29)" :key="index + item">
Nee, das ist Vue-syntax (https://vuejs.org/guide/essentials/list.html) an dieser Stelle

2022-10-17 10:48 UTC, roriwa approved these changes
wenn du sagst das passt, dann darfst du

2022-10-17 11:51 UTC, merged