Better readme svg
konstantinlob/What-am-I-listening-to pull request #67
Opened 2022-10-17 15:44 UTC by JuliusJaenchen

2022-10-17 15:47 UTC, roriwa requested changes

2022-10-17 15:47 UTC, roriwa commented on README.md
> +# <img src="README.assets/WAILT_logo_black_background.svg" alt="What-Am-I-Listening-To-Logo" style="height: 2rem; background-color: black; border-radius: 50%; padding: 1px;" /> What am I listening to
alt bitte nur wenns sinn macht. hier ist es unnötig

2022-10-18 08:39 UTC, JuliusJaenchen commented on README.md
> +# <img src="README.assets/WAILT_logo_black_background.svg" alt="What-Am-I-Listening-To-Logo" style="height: 2rem; background-color: black; border-radius: 50%; padding: 1px;" /> What am I listening to
Eigentlich sollte man sich zur Gewohnheit machen _immer_ ein at Logo hinzuzufügen aus accessability Gründen. So ist es deutlich besser für Menschen mit Behinderungen und hilft ggf bei der SEO. Und hier macht es ja kaum ein Unterschied...

2022-10-18 09:32 UTC, roriwa approved these changes

2022-10-18 09:33 UTC, merged